import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-8 bg-purple-500">
           <Link href="/showproducts" className="hover:bg-purple-700 hover:text-white">Show Products
      </Link>
        <Link  href="/insertproducts " className="hover:bg-purple-700 hover:text-white">Add Products </Link>
  </nav>
     
        {children}</body>
    </html>
  );
}
